A2 557 FINAL/FashionLookout/views.py
from flask import Blueprint, render_template,  request, session, flash,url_for,redirect,jsonify
from .models import Product, Cart, Order
from datetime import datetime
from .forms import CheckoutForm
from . import db

main_bp = Blueprint('main', __name__)

@main_bp.route('/')
def index():
    products = db.session.scalars(db.select(Product).order_by(Product.id)).all()
    #title = "Fashion Lookout Home"
    return render_template('ecommerce.html', products=products)


#@main_bp.route('/products/<int:product_id>')
#def products(product_id):
    #products = db.session.scalars(db.select(Product).where(Product.product_id==product_id)).all()
    products = Product.query.order_by(Product.id).all()
    return render_template('products.html', products=products)

#@main_bp.route('/products', methods=['GET'])
#def all_products():
    # 假設你的資料庫模型名稱為Product
    products = Product.query.all() 
    return render_template('products.html', products=products)

@main_bp.route('/products/', defaults={'product_id': None})
@main_bp.route('/products/<int:product_id>')
def products(product_id):
    
    if product_id is None:
        # get all products
        products = Product.query.all()
    else:
        products = Product.query.filter(Product.id == product_id)
   
    #productDetails = db.session.scalar(db.select(Product).where(Product.id==product_id))
    return render_template('products.html', products=products)


# ****** SEARCH ROUTE *******
@main_bp.route('/products')
def search():
 search = request.args.get('search')
 search = '%{}%'.format(search)
 products = Product.query.filter(Product.description.like(search)).all()
 return render_template('products.html', products=products)


# Referred to as "Basket" to the user
@main_bp.route('/shoppingbasket', methods=['POST', 'GET'])
def shoppingbasket():
    title = "Fashion Lookout Shopping Basket"
    product_id = request.values.get('product_id')
    print(f'Values: {product_id}')

 # retrieve order if there is one
    if 'order_id' in session.keys():
        order = db.session.scalar(db.select(Order).where(Order.id==session['order_id']))
        # order will be None if order_id/session is stale
    else:
            # there is no order
            order = None
    
    
    # create new order if needed
    if order is None:
        order = Order(status=False, date=datetime.now(), total_cost=0, first_name='', surname='', email='', phone='', address='')
        try:
            db.session.add(order)
            db.session.commit()
            session['order_id'] = order.id
        except:
            print('Failed trying to create a new order!')
            order = None
    
    # calculate total price
    total_cost = 0
    if order is not None:
        for product in order.products:
            total_cost += product.price
    
# are we adding an item?
    if product_id is not None and order is not None:
        product = db.session.scalar(db.select(Product).where(Product.id==product_id))
        if product not in order.products:
            try:
                order.products.append(product)
                db.session.commit()
            except:
                flash('There was an issue adding the item to your basket',category='danger')
            return redirect(url_for('main.shoppingbasket'))
        
    return render_template('shoppingbasket.html', order=order, total_cost=total_cost, title=title)


# Delete specific basket items
# Note this route cannot accept GET requests now
@main_bp.route('/deletebasketitem', methods=['POST'])
def deletebasketitem():
    id = request.form['id']
    if 'order_id' in session:
        order = db.get_or_404(Order, session['order_id'])
        product_to_delete = db.session.scalar(db.select(Product).where(Product.id==id))
        try:
            order.products.remove(product_to_delete)
            db.session.commit()
            return redirect(url_for('main.shoppingbasket'))
        except:
            return 'Problem deleting item from order'
    return redirect(url_for('main.shoppingbasket'))

# Scrap basket
@main_bp.route('/deletebasket')
def deletebasket():
    if 'order_id' in session:
        del session['order_id']
        flash('All items deleted')
    return redirect(url_for('main.index'))

# FINAL CHECKOUT ROUTE Complete the order
@main_bp.route('/checkout', methods=['POST','GET'])
def checkout():
    form = CheckoutForm() 
    if 'order_id' in session:
        order = db.get_or_404(Order, session['order_id'])
        if form.validate_on_submit():
            order.status = True
            order.date = datetime.now()
            order.first_name = form.first_name.data
            order.surname = form.surname.data
            order.email = form.email.data
            order.phone = form.phone.data
            order.address = form.address.data
            total_cost = 0
            for product in order.products:
                total_cost += product.price
            order.total_cost = total_cost
            
            try:
                db.session.commit()
                del session['order_id']
                flash('Thank you for your purchase! Order is being processed. We will notify you when it is shipped.')
                return redirect(url_for('main.index'))
            except:
                return 'There was an issue completing your order'
    return render_template('checkout.html', form=form)

A2 557 FINAL/FashionLookout/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{% block title %}Default Title{% endblock %}</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
        integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

   

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/mystyle.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />



</head>

<body>

    <header>
        <!--NAVIGATION BAR-->
        <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #ffffff;">
            <a class="navbar-brand" href="#">
                <img src="{{ url_for('static', filename='Images/fashionlogo.png') }}"width="30" height="30" class="d-inline-block align-top" alt="logo">
                Fashion Lookout</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{{ url_for('main.index') }}">Home <span class="sr-only">(current)</span></a>
                    </li>
                
                    <li class="nav-item">
                        <a class="nav-link" href="#">About Us</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link" href="{{ url_for('main.products') }}" role="button">
                            Products
                        </a>
                    </li>
                    
                </ul>

                <div class="searchBox">
                    <form action="{{url_for('main.search')}}">
                        <input class="searchInput" id="searchbar" type="text" name="search" placeholder="Search products">
                        <button class="btn btn btn-secondary btn-s my-0 ml-1" id="searchbutton" type="submit">Search</button>
                    </form>
                </div>

                <div class="icons">
                    <button type="button" class="btn default">
                        <a href="#" role="button" aria-pressed="true">
                            <img src="{{ url_for('static', filename='Images/user.png') }}"width="35" height="35" class="d-inline-block align-top"
                                alt="logo">
                        </a>
                    </button>
                </div>

                <div class="icons">
                    <button type="button" class="btn default">
                        <a href="{{ url_for('main.shoppingbasket') }}" role="button" aria-pressed="true">
                            <img src="{{ url_for('static', filename='Images/carticon.png') }}" width="28" height="28" class="d-inline-block align-top" alt="logo">
                        </a>
                    </button>
                </div>
                

            </div>
        </nav>

        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="alert alert-primary m-2" role="alert">
            {% for message in messages %}
                {{message}}
            {% endfor %}
            </div>
        {% endif %}
        {% endwith %} 

        </header>

    <!-- Page Content -->
    
        <main>
            {% block main %}
            
            {% endblock %}
        </main>
   
    <!-- Footer -->
    <footer>
        <div class="footer">
            <div class="containerfooter">
                <div class="row" id="footer-row">
                    <div class="footer-col col-6 col-md-3 col-lg-3">
                        <h4>About Us</h4>
                        <ul>
                            <li><a href='#'>Our Story</a></li>
                            <li><a href='#'>Careers</a></li>
                            <li><a href='#'>Sustainability</a></li>
                            <li><a href='#'>News</a></li>
                        </ul>
                    </div>
                    <div class="footer-col col-6 col-md-3 col-lg-3">
                        <h4>Help</h4>
                        <ul>
                            <li><a href='#'>FAQ</a></li>
                            <li><a href='#'>Shipping</a></li>
                            <li><a href='#'>Returns Policy</a></li>
                            <li><a href='#'>Privacy Policy</a></li>
                            <li><a href='#'>Terms and Conditions</a></li>
                        </ul>
                    </div>
                    <div class="footer-col col-6 col-md-3 col-lg-3">
                        <h4>Account</h4>
                        <ul>
                            <li><a href='#'>Membership</a></li>
                            <li><a href='#'>Profile</a></li>
                            <li><a href='#'>Coupons</a></li>
                        </ul>
                    </div>
                    <div class="footer-col col-6 col-md-3 col-lg-3">
                        <h4>Connect with Us</h4>
                        <div class="social-links">
                            <a href='#'><i class="fa-brands fa-facebook"></i></a>
                            <a href='#'><i class="fa-brands fa-instagram"></i></a>
                            <a href='#'><i class="fa-brands fa-twitter"></i></a>
                            <a href='#'><i class="fa-brands fa-youtube"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row justify-content-center" id="footer-row">
                <span class="text-dark"> Copyright &copy; Fashion Lookout 2023</span>
            </div>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</body>

</html>

A2 557 FINAL/FashionLookout/templates/checkout.html
{% extends 'base.html' %}
{% block title %}Checkout{% endblock %}

{% from 'bootstrap4/form.html' import render_form %}


{% block main %}
    <section>  
        <div class="container ">
            <div class="row" id="checkout" style="justify-content: center;">
                <div class = "col-12 text-center">
                    <h1>Place Your Order</h1>
                    <h5>
                        Please provide your details below to checkout your order. Thank you!
                    </h5><br>
                </div>
            </div>
            <div class="row">
                <div class = "col-10">
                    {{render_form(form)}}
                </div>
            </div>
        </div>
    </section>
</main>
{% endblock %}

A2 557 FINAL/FashionLookout/templates/ecommerce.html
{% extends 'base.html' %}

{% block title %}Home page {% endblock %}

{% block main %}
    <!-- JUMBOTRON -->
    <div class="jumbotron" id="headingjumbotron" style="background-image: url({{url_for('static', filename='Images/jumbotron1.png')}})";>
      <div class="heading">
        <div class="col-12 col-sm-6 col-md-6 col-lg-6">
          <h1 class="display-4">Spring 2023</h1>
          <h1 class="display-4">Collection</h1>
          <p></p>
        </div>
        <div class="col-8 col-sm-6 col-md-6 col-lg-12">
          <h2 class="lead">Intuitive. Adaptable. Expressive</h2>
          <p></p>
        </div>

        <div class="col-6 col-sm-6 col-md-4 col-lg-4" style="font-size: 18px; margin-top: 20px;">
          <p>Ready for any twist in your day, in soft and dynamic styles. Our new season range is a favourite.</p>
        </div>

        <a href="{{url_for('main.products')}}"><button class="jumbo headerbutton">View Details</button></a>
      </div>
    </div>
  </header>

  <!-- FIRST CONTENT BEST SELLER -->
  <main>
    <div class="content1">
        <h3 class="bestseller">Best Sellers</h3>
        <p style="font-size: 18px;"> From everyday staples to standout pieces, we have something to suit every occasion.
        </p>
    </div>
    <div class="container-fluid">
        <div class="row">

          {% for product in products %}

            <!-- Product 1 -->
            <div class="col-6 col-md-6 col-lg-3 mt-4">
                <div class="card h-100">
                  <a href="{{ url_for('main.products') }}"><img src="{{url_for('static', filename='Images/'+product.image)}}"
                            class="card-img-top" alt="Product Image" style="width:100%"></a>
                    <div class="card-body">
                        <a class="nav-link productname" href="{{ url_for('main.products') }}">
                            <button class="card-title">{{product.name}}</button>
                        </a>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                          <line style="font-size: 18px">Price: ${{product.price}}</line>
                        </li>
                    </ul>
                    <form action="{{url_for('main.products')}}">
                        <button type="submit" class="btn addcart" id="detailsbutton">
                              <input type="hidden" id="product_id" name="product_id" value="{{product.id}}">
                              <input class="btn" type="submit" value="View Details">
                        </button>
                      </form>
                </div>
            </div>

            {% endfor %}

                       
        </div>
    </div>
</main>

    <!-- SUBSCRIBE JUMBOTRON -->
    <div class="jumbotron jumbotron-fluid" id="subscribe" style="background-color: rgba(232, 210, 187, 0.75);">
      <div class="container">
        <h3>Become a member to get 10% off your next purchase</h3>
        <p class="lead">Plus free shipping and returns on orders over $60. Join now, it's free!</p>
        <a href="#"><button class="jumbo headerbutton" id="memberbutton">Join Membership</button></a>
      </div>
    </div>

    <!-- PRODUCT CATEGORY CONTENT -->
    <div class="content1">
      <h3 class="bestseller" style="margin-top: 30px; margin-bottom: 10px;">Product Categories</h3>
    </div>

    <div class="container-fluid">
      <div class="row" id="category-card">
        <div class="col-6 col-md-6 col-lg-3 mt-4">
          <div class="card">
            <img src="{{ url_for('static', filename='Images/tops.png') }}" class="card-img-top" alt="Tops">
            <div class="card-body">
              <a href="{{ url_for('main.products') }}"><h5 class="card-text">Tops</h5></a>
            </div>
          </div>
        </div>
        <div class="col-6 col-md-6 col-lg-3 mt-4">
          <div class="card">
            <img src="{{ url_for('static', filename='Images/bottoms.png') }}" class="card-img-top" alt="Bottoms">
            <div class="card-body">
              <a href="{{ url_for('main.products') }}"><h5 class="card-text">Bottoms</h5></a>
            </div>
          </div>
        </div>
        <div class="col-6 col-md-6 col-lg-3 mt-4">
          <div class="card">
            <img src="{{ url_for('static', filename='Images/outerwear.png') }}" class="card-img-top" alt="Outer/Jumper">
            <div class="card-body">
              <a href="{{ url_for('main.products') }}"><h5 class="card-text">Outer/Jumper</h5></a>
            </div>
          </div>
        </div>
        <div class="col-6 col-md-6 col-lg-3 mt-4">
          <div class="card">
            <img src="{{ url_for('static', filename='Images/accessories.png') }}" class="card-img-top" alt="Accessories">
            <div class="card-body">
              <a href="{{ url_for('main.products') }}"><h5 class="card-text">Accessories</h5></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>

  {% endblock %}

A2 557 FINAL/FashionLookout/templates/error.html
{% extends 'base.html' %}

{% block title %}Error page{% endblock %}

{% block main %}
    <div class="container">
        <h1>Error</h1>
        <p>Sorry, but something went wrong!</p>
        <p>More info: {{error}}</p>
    </div>
{% endblock %}

A2 557 FINAL/FashionLookout/templates/products.html
{% extends 'base.html' %}

{% block main %}
<!-- display tours for the specific city -->
<section>

    <div class="text-dark text-center">
        <div>
            <p class="h3 text-dark mb-4">Our Products</p>
        </div>
    </div>

    <div class="container-fluid">
        
        <div class="row">
            {% for product in products %}
            <div class="col-6 col-md-6 col-lg-3 mt-4">
                <!-- each tour is a bootstrap card -->
                
                <div class="card h-100">
                    <img class="card-img-top" src="{{url_for('static', filename='Images/'+product.image)}}" alt="Card image">
                    <div class="card-body">
                        <h4 class="card-title">{{product.name}}</h4>
                        <p class="card-text">{{product.description}}</p>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            <h5>Price: ${{product.price}}</h5>
                        </li>
                        <li class="list-group-item">
                            <h6>Sizes: {{product.size}}</h6>
                        </li>
                        <li class="list-group-item">
                            <h6>Color: {{product.color}}</h6>
                        </li>
             
                        <li class="list-group-item">
                            <h6>Material: {{product.material}}</h6>
                        </li>
                    </ul>
                    <div class="card-footer">
                        
                            <button id="addtocartbutton">
                                <form action="{{url_for('main.shoppingbasket')}}">
                                <input type="hidden" id="product_id" name="product_id" value="{{product.id}}">
                                <input class="btn" type="submit" value="Add to Basket">
                                </form>
                            </button>
                        
                    </div>
                    
                </div>
                
            </div>
            {% endfor %}
        </div>
        
    </div>     

</section>
{% endblock %}

A2 557 FINAL/FashionLookout/templates/shoppingbasket.html
{% extends 'base.html' %}

{% block title %}Shopping Basket{% endblock %}

{% block main %}
<main class="container mt-5 text-center">
    <div class="row justify-content-center">
        <div class="col-lg-10">
            <div class="container-fluid">  <!-- 加入 container-fluid 保護內部元素 -->
                <h2 class="mb-4" id="titleshoppingbasket">Your Shopping Basket</h2>

                
                <!-- Cart Items -->
                {% for product in order.products %}
                <div class="item-container" id="boxbasket">
            <div class="row shadow-md my-row mb-3">
                <div class="col-sm-10 col-md-10 card">
                    <h5 class="card-header">{{product.name}}</h5>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-12 col-md-6 col-lg-6">
                                <img class="img-thumbnail" src="{{url_for('static', filename=('Images/' + product.image))}}">
                            </div>
                            <div class="col-sm-12 col-md-6 col-lg-6" style="text-align: left;" id="cartcontent">
                                <!-- Item Description -->
                                <p class="card-text">Description:</p>
                                <hr>
                                <p class="card-text">{{product.description}}</p>
                                <br><p class="card-text">Material:</p>
                                <hr>
                                <p class="card-text">{{product.material}}</p>     
                            </div>  
                        </div>                      
                    </div>
                </div>
                <br><br>
                <!-- right column has price and delete button -->
                <div class="col-sm-2">
                <!-- delete item button -->
                    <h5 class="mt-2">Price: {{"$%.2f"|format(product.price)}}</h5>
                    <form method="POST" action="{{url_for('main.deletebasketitem')}}">
                        <input type="hidden" id="id" name="id" value="{{product.id}}">
                        <input type="submit" value="Delete" class="btn mb-3" id="deleteitem">
                    </form> 
                </div>
            </div>
        </div>
        {% endfor %}

         <!-- total price and page controls -->
         <section>
            <div class="row col-12">
                <h5 class="mt-4 d-flex">Total Price = {{"$%.2f"|format(total_cost)}}</h5>
            </div>
            <hr>
            <div class="row co-12 d-flex mt-2 mb-5">
                <a href="{{url_for('main.deletebasket')}}" class="btn mr-4" id="emptybasket">Empty Basket</a>
                
                <a href="{{url_for('main.products', _anchor='products_anchor')}}" class="btn mr-4" id="addproducts">Add More Products</a>

                <a href="{{url_for('main.checkout')}}" class="btn mr-4" id="proceedcheckout">Proceed to Checkout</a>
            </div>
        </section>

            </div>
        </div>
    </div>
</main>
{% endblock %}